msg_coordinate = '위치: ';
msg_character = '명령: ';
msg_input_number = '숫자를 입력하세요. 실행을 일시 정지하려면 !!!를 입력하세요.';
msg_input_character = '글자를 입력하세요. 실행을 일시 정지하려면 [취소]를 누르세요.';
txt_stopped = '<font color="red">정지됨</font>';
txt_running = '<font color="green">실행중</font>';
txt_paused = '일시 정지됨';
txt_run = '실행';
txt_pause = '일시 정지';
txt_continue = '계속';
